-- Sample INSERT statements for the products table
-- This includes all the ingrediants for one recipe
INSERT INTO products (supermarket, item_id, product_name, product_desc, sales_unit, price_per_uom, price)
VALUES
    ('Asda', 'ASDA123', 'Harissa Paste', 'Spicy condiment', 'Per Jar', '2.99', '1.99'),
    ('Asda', 'ASDA789', 'Ground Cumin', 'Essential spice for cooking', 'Per Gram', '0.03', '1.49'),
    ('Asda', 'ASDA101', 'Ground Cumin', 'High-quality spice for flavor', 'Per Gram', '0.08', '2.99'),
    ('Asda', 'ASDA202', 'Ground Cumin', 'Premium spice for gourmet dishes', 'Per Gram', '0.12', '5.49'),
    ('Asda', 'ASDA303', 'Red Onions', 'Fresh red onions', 'Per Kilogram', '0.99', '1.99'),
    ('Asda', 'ASDA404', 'Red Onions', 'Organic red onions', 'Per Kilogram', '1.29', '2.49'),
    ('Asda', 'ASDA505', 'Red Onions', 'Premium red onions', 'Per Kilogram', '1.59', '3.99'),
    ('Asda', 'ASDA309', 'Brown Onions', 'Fresh brown onions', 'Per Kilogram', '0.99', '1.99'),
    ('Asda', 'ASDA407', 'Brown Onions', 'Organic brown onions', 'Per Kilogram', '1.29', '2.49'),
    ('Asda', 'ASDA511', 'Brown Onions', 'Premium brown onions', 'Per Kilogram', '1.59', '3.99'),
    ('Asda', 'ASDA606', 'Skinless Chicken Breasts', 'Fresh skinless chicken breasts', 'Per Kilogram', '6.99', '9.99'),
    ('Asda', 'ASDA707', 'Skinless Chicken Breasts', 'Free-range skinless chicken breasts', 'Per Kilogram', '8.99', '12.99'),
    ('Asda', 'ASDA808', 'Skinless Chicken Breasts', 'Organic skinless chicken breasts', 'Per Kilogram', '10.99', '15.99'),
    ('Asda', 'ASDA909', 'Small Butternut Squash', 'Fresh small butternut squash', 'Per Piece', '1.49', '1.99'),
    ('Asda', 'ASDA1010', 'Small Butternut Squash', 'Organic small butternut squash', 'Per Piece', '2.49', '2.99'),
    ('Asda', 'ASDA1111', 'Small Butternut Squash', 'Locally sourced small butternut squash', 'Per Piece', '1.99', '2.49'),
    ('Asda', 'ASDA1212', 'Canned Tomatoes', 'Regular diced canned tomatoes', 'Per Can', '0.99', '1.29'),
    ('Asda', 'ASDA1313', 'Canned Tomatoes', 'Organic crushed canned tomatoes', 'Per Can', '1.29', '1.79'),
    ('Asda', 'ASDA1414', 'Canned Tomatoes', 'Fire-roasted canned tomatoes', 'Per Can', '1.49', '1.99'),
    ('Asda', 'ASDA1515', 'Lemons', 'Fresh regular lemons', 'Per Kilogram', '2.49', '3.99'),
    ('Asda', 'ASDA1616', 'Lemons', 'Organic lemons', 'Per Kilogram', '3.99', '4.99'),
    ('Asda', 'ASDA1717', 'Lemons', 'Large, juicy lemons', 'Per Kilogram', '2.99', '3.49'),
    ('Asda', 'ASDA1818', 'Cherry Tomatoes', 'Fresh cherry tomatoes', 'Per Pack', '1.99', '2.49'),
    ('Asda', 'ASDA1919', 'Cherry Tomatoes', 'Organic cherry tomatoes', 'Per Pack', '2.49', '2.99'),
    ('Asda', 'ASDA2020', 'Cherry Tomatoes', 'Mixed colors cherry tomatoes', 'Per Pack', '2.29', '2.79'),
    ('Asda', 'ASDA2121', 'Couscous', 'Regular couscous', 'Per Pack', '0.99', '1.29'),
    ('Asda', 'ASDA2222', 'Couscous', 'Whole wheat couscous', 'Per Pack', '1.49', '1.79'),
    ('Asda', 'ASDA2323', 'Couscous', 'Herbed couscous', 'Per Pack', '1.29', '1.59'),
    ('Asda', 'ASDA2424', 'Coriander', 'Fresh coriander bunch', 'Per Bunch', '0.99', '1.29'),
    ('Asda', 'ASDA2525', 'Coriander', 'Organic coriander bunch', 'Per Bunch', '1.49', '1.79'),
    ('Asda', 'ASDA2626', 'Coriander', 'Fresh coriander leaves', 'Per Bunch', '1.29', '1.59'),
    ('Asda', 'ASDA2727', 'Garlic', 'Fresh garlic bulbs', 'Per Bulb', '0.49', '0.69'),
    ('Asda', 'ASDA2828', 'Garlic', 'Organic garlic bulbs', 'Per Bulb', '0.79', '0.99'),
    ('Asda', 'ASDA2929', 'Garlic', 'Garlic powder', 'Per Gram', '0.02', '0.49'),
    ('Asda', 'ASDA3131', 'Olive Oil', 'Extra virgin olive oil', 'Per Bottle', '4.99', '7.99'),
    ('Asda', 'ASDA3232', 'Olive Oil', 'Organic olive oil', 'Per Bottle', '5.99', '9.99'),
    ('Asda', 'ASDA3333', 'Olive Oil', 'Cold-pressed olive oil', 'Per Bottle', '6.99', '11.99');
